## @file dll_types.py
#
# @author Leonardo Ricupero

import enum


class EnumClientErrors(enum.IntEnum):
    CLIENT_NOERRORS = 0
    CLIENTERROR_SERVERNORESPONCE = 1
    CLIENTERROR_SERVERINVALIDCODE = 2
    CLIENTERROR_SERVERINVALIDLENGTH = 3
    CLIENTERROR_TCPIPCONNECTION = 4
    CLIENTERROR_INVALIDACQFILE = 5
    CLIENTERROR_MISMATCHPACKETERROR = 6
    CLIENTERROR_INVALIDDATAFILE = 7
    CLIENTERROR_OPENTOOLSCOMM = 8
    CLIENTERROR_OPENDEVICESSCOMM= 9
    CLIENTERROR_AIDAINVALIDVERSION = 10
    CLIENTERROR_AIDANOADA2FOUND = 11
    CLIENTERROR_TOOLSCOMMALREADYOPEN = 12
    CLIENTERROR_DEVICESSCOMMALREADYOPEN = 13
    CLIENTERROR_DEVICESSERVERINVALIDCODE = 14
    CLIENTERROR_AIDASERVERNOTINIT = 15
    CLIENTERROR_DEVICESSERVERNOTINIT = 16
    CLIENTERROR_INPUTDATANOTVALID = 17    
    CLIENTERROR_FUNCTIONNOTWORKING = 18
    CLIENTERROR_WRONGMETACOMMAND = 19
    CLIENTERROR_NOMATCHINGGROUPS = 20
    CLIENTERROR_TOOMUCHDATA = 21
    CLIENTERROR_AIDAERROR = 22
    CLIENTERROR_INVALIDMETAFILE = 23
    CLIENTERROR_INSTRUMENTNOTFOUND = 24
    CLIENTERROR_INVALIDSETTINGFILE = 25
    CLIENTERROR_MISMATCHPACKETSETTINGERROR = 26
    CLIENTERROR_NUM_ERRORS = 27
