[LINKS]
Report_ID = 1XcaLoVCFfaZdcVmn533iCEqechTh636P 
Acquisitions_ID = 1nQI4MU5kowGxPEEloZEDtT_iC78mF5Mu

[REPORT]
Name = Himalaya_PV_ID18

# optional parameters
# Complete   = YES  
# Prefaults  = YES
# FilterDoor = YES
# StartDate  = string format yyyymmdd 
# EndDate    = string format yyyymmdd

