# -*- coding: utf-8 -*-
"""Find_MCI_Errors_and_prefaults.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dSqPCf1LBxw8WUIumM5WMaQYu3CQRSEm
"""

#### PYTHON 2 ONLY ####
#### INSTALL PyDrive  #####
!pip install -U -q PyDrive
#### upgrade pygsheet
!pip install --upgrade -q pygsheets


from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

####  Authenticate and create the PyDrive client.   #####
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

#### Authenticate and create pygsheet client.
import pygsheets
gc = pygsheets.Client(GoogleCredentials.get_application_default())

#### General Imports  ####
import pandas as pd
from io import StringIO

mac_utilities_lib_id = '1oNEf1ItURF7ybJd0t7sTid6BNI518O68'
mac_class_id = '1yOrlMAZMXTjakNvg-MFsi4sXq9iYwsvq'
mac_utilities_lib = drive.CreateFile({'id': mac_utilities_lib_id})
mac_utilities_lib.GetContentFile('mac_utilities.py')
mac_class = drive.CreateFile({'id': mac_class_id})
mac_class.GetContentFile('mac_class.py')
import mac_utilities as mac_lib
from mac_class import *

"""#  Files and Folder Management"""

# Report folder
rep_folder_id = '1Ep5xMf_-j5I38SrSlP9RDdbUs4RPGZdo'
# mac folder (subfolder will be scanned as well) - it can be even a file
mac_folder_id = '1k0-C3-6gxS92Lon7OZpFJYWwAGbO9MPQ'   ## all acquisition
#mac_folder_id = '1vf5G1VrBla3gge4niwBsbd_4J3v2F1HN'    ## one folder
#mac_folder_id = '1fMmRW5UskmRiSp3vx9V4qselZqNs4zxY'    ## just one file



# create the list of files to be processed
#check if mac folder id is a single file
mac_file = drive.CreateFile({'id': mac_folder_id})
if mac_file['mimeType']=='application/vnd.google-apps.folder':
  #it is a folder
  file_list = mac_lib.search_files_in_drive(drive, mac_folder_id, '.mac')
else:
  #it is a single file: check if it is a mac file
  if mac_file['title'].endswith('.mac'):
    file_list = [mac_file]

"""# Core Algorithm and report generation"""

complete_report = True
prefault_analysis = True
### create the spreadsheet report  ###
import datetime
now = datetime.datetime.now()
title = 'report_'+ str(now)
report = gc.create(title, rep_folder_id)
#rename the first sheet
report.sheet1.title='report'
report_ws = report.sheet1
# create first row (header)
recap_header = ['Acquisition', 'ACU', 'MCU', 'Setting Part', 'Gese Version','Folder', 'Mci errors', 'Prefaults', 'Details', 'Duration']
row_recap = 1
report_ws.insert_rows(row=row_recap, values=recap_header)
row_recap +=1
back_to_first_str = ['=HYPERLINK("#gid=%s","Back to first page")' %(str(report_ws.id),)]

for file in file_list:
  file_id   = file['id']
  file_name = file['title']
  
  # create the mac object
  mac_obj = MacObject((drive,file_id))
  
  try:
    ### extra machine info ###
    acq_str = '=HYPERLINK("%s","%s")' %(file['alternateLink'],file['title'])
    folder_id = drive.CreateFile({'id': file['parents'][0]['id']})
    machine_info = [acq_str, mac_obj.acu_info['fw_v'],mac_obj.mcu_info['fw_v'],mac_obj.acu_info['setting_n'], mac_obj.acu_info['gese_v'], folder_id['title']]

    ### Extract data from win log ###
    win_log_data_df = mac_obj.extract_win_log()
    results = mac_lib.process_df(win_log_data_df,'MCI_errors_API220_log')
    duration = [str(pd.to_datetime(win_log_data_df['Time'].iloc[-1]) - pd.to_datetime(win_log_data_df['Time'].iloc[0]))]

    ### get recap data from result ###
    recap_data = mac_lib.recap_results(results,'MCI_errors_API220_log')


    if prefault_analysis:
      ### Extract data from acquisition (prefaults)  ###
      acq_data_df = mac_obj.extract_acq()
      prefault_results = mac_lib.process_df(acq_data_df,'Prefault')
      ### get recap data from result ###
      prefault_recap_data = mac_lib.recap_results(prefault_results,'Prefault')
    else:
      prefault_recap_data = ['-']



    if complete_report:
      ### write to spreadsheet - mci errors ###
      wks_new = report.add_worksheet(file_name)
      wks_new.insert_rows(row=1, values = back_to_first_str)
      wks_new.set_dataframe(results, (3, 1))

      if prefault_analysis:
        ### write to spreadsheet - prefaults ###
        wks_new.set_dataframe(prefault_results[['DateTime','Prefault']],(len(results)+10,1))


      link_details = ['=HYPERLINK("#gid=%s","%s")' %(str(wks_new.id),file['title'])]
    else:
      link_details = ['-']

    ### update the recap sheet ###
    report_ws.insert_rows(row=row_recap, values=machine_info + recap_data + prefault_recap_data + link_details + duration)
    
  except Exception as ex:
    row_recap +=1
    report_ws.insert_rows(row =row_recap, values = ['error while processing '+ file_name + ' acquisition'])
    template = "An exception of type {0} occurred. Arguments:\n{1!r}"
    message = template.format(type(ex).__name__, ex.args)
    print message
    
  row_recap +=1

