# -*- coding: utf-8 -*-
"""Python3_Find_MCI_Errors_and_prefaults_v2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gPs52wjpVVy5-1aofOhWtp-PsfgDMdh7
"""

#### PYTHON 3 ONLY ####
# reference documentation from here https://www.pingshiuanchua.com/blog/post/intro-to-colaboratory-and-linking-it-to-google-sheets
#### INSTALL PyDrive  #####
!pip install -U -q PyDrive2     ## required in order to work with Shared Drives --> see here https://stackoverflow.com/questions/58915550/pydrive-download-file-from-a-shared-drive
#### upgrade pygsheet
!pip install --upgrade -q pygsheets
#!pip install pygsheets==1.1.4 #last stable version supporting python2

from pydrive2.auth import GoogleAuth
from pydrive2.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

####  Authenticate and create the PyDrive client.   #####
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

#### Authenticate and create pygsheet client.

import google.auth
auth.authenticate_user()
import pygsheets
credentials, _ = google.auth.default()
gc = pygsheets.client.Client(credentials)

#### General Imports  ####
import pandas as pd
from io import StringIO
import re   
#original files are in https://drive.google.com/drive/u/0/folders/1aEuF8QTVhQs0V1w2RxqSntT7vI2DVrOr
mac_utilities_lib_id = '1Xh_0txOrwp1CjkzVwezVAdGnjFFkmaEm'
mac_class_id = '1bbkvZhj0cjHO1e6UaZRQtAuDMAIwuwh8'
mac_utilities_lib = drive.CreateFile({'id': mac_utilities_lib_id})
mac_utilities_lib.GetContentFile('mac_utilities_3.py')
mac_class = drive.CreateFile({'id': mac_class_id})
mac_class.GetContentFile('mac_class_3.py')
import mac_utilities_3 as mac_lib
from mac_class_3 import *

"""#  Files and Folder Management"""

# Report folder
#rep_folder_id = '1E1gzfF1N5he6f94tSIXI9VC-QUa5sMXE'   # report for Majesty China folder
#rep_folder_id = '1E6g1TtOBTzoZuMHXrT-0Gp3f-maTr1yR'   #report for Premium project 
#rep_folder_id = '1HFN2tAvw23V2zBtTU42oq77en-uI8DO7'    # detailed report for Premium project
#Premium performance lab PV machine
#rep_folder_id = '1ZWk1ednZoWAlTvFhDGQ_pKjtU1mhhfau'
#Iguazu
rep_folder_id = '1XcaLoVCFfaZdcVmn533iCEqechTh636P'     # Iguazu\Himalaya project
#mac_folder_id =  '1Ehc91HY2Vj-caTFA4ICYDgINUaGdBRx2'   # acquisition for Majesty China project
#mac_folder_id = '1duEKkRYhfeD7FOMnpJ2j2wTNp52Gc8K0'   # Premium mechanical test TEM9
#mac_folder_id = '1O5la-MkZ3ca2CwjqAw5lTZT-f-STovcw'   # Premium mechanical test TEM1
#mac_folder_id = '1vWsfk1TFOLv2D-MQmXDLM_c8ZyRJhzDE' # Premium R&S test TEM9
#mac_folder_id = '1y4QhupQtb4yYvCkX6018eChwAUtHtx5f' # Premium R&S test TEM1
#mac_folder_id = '1LfQ6JUfyYCnQpPK_luap9LVxeGqRY-0H'  # Premium Consumer test TEM5
#mac_folder_id = '1SD2c5PXduc7o-Yhw_xCyUo7uUxqbNoy9'  # Premium Consumer test TEM12
#mac_folder_id = '1foYtF7mXVoduQ0qO3A6ZYyqftC68GzqJ'  # Premium CQL
#mac_folder_id = '1cUqMGFKkWV2dWSMfxBKLRWPx5_2-ufpR'   # Premium CQL PV machines 
#mac_folder_id = '178gYrubCatzmXZ-KMUVuM6sku9yk7Ycx' 
#mac_folder_id = '1_1BWM90vQZPvxOgTByj9rzP_30Ognjg7'   #Premium PV1 Poprad
#mac_folder_id = '1_3Unlnb1XMzzlyN6Ntu5Iz8jPst4lCk5'   #Premium PV1 Poprad C90 + Steamtest
#mac_folder_id = '1Zu_ZM65PjTkKPLuljwXRCvVl-TVo6gJF'    #Premium PV1 Poprad consumer test
#mac_folder_id = '1o-V14BcyNn6boqoxb90EiV-PjQ1KT1tl'     # Premium PV1 Poprad Steam test folder
#Premium performance lab PV machine
#mac_folder_id  = '1ZWk1ednZoWAlTvFhDGQ_pKjtU1mhhfau'

#mac_folder_id = '1Kiz5oq00j6Z005BVGcQh1jsFgzM3y2aO'     #Premium PV1 CQL TEM12
#mac_folder_id = '12MsBhX2DbcErl9wIMIX-fH8Vj8bpIl6c'     # Premium PV2 Comunanza

#mac_folder_id = '1Tpo1C2zt91rcmpaAY_aPmdwQY7QhOon6'       #single file for quick test

#mac_folder_id = '1Gq9G4nfztMP29OOjPkFfp8L-Xn50mC1b'       # Iguazu project (All reliability folder)
mac_folder_id = '1CrG5NcNrKDFF-mS8zc71sl4sLGsEFTAi'       # Iguazu TEM5
mac_folder_id = '199C3VtKbKkYWGhh2d05yDxTz3hqC6wLo'       # Iguazu TEM4
#mac_folder_id = '1Moopub6iusMH4UIWmfM0If1yvlElSeho'       # Himalaya acquisitions
#mac_folder_id = '1LFyDisKcgjnAp5feqVVB73HvWXVSiCGu'       # Himalaya Cotton60
#mac_folder_id = '1MRHuJaR08750JabPQBTZ93mb4C4NSYem'       #Himalaya Dryspin1

# FILES FOR TESTING THE NEW VERSION ############################
#mac_folder_id = '1-ZbNPeoCE06E1mmtJN1FZKn-eUDuhZgK'
#mac_folder_id = '1P0Hn-mn8HJYXmbGoQ3KHF1zBiDJ73Pq7'
#mac_folder_id = '1I0xsxEHaFQK8QA2HDZSV6L0ZD85wZUE3'     #no error
#mac_folder_id = '15dFvne2rr6cfs1g4_viorSsyKpsYkGM4'
################################################################
# create the list of files to be processed
#check if mac folder id is a single file
mac_file = drive.CreateFile({'id': mac_folder_id})
#print(mac_file.GetPermissions())
if mac_file['mimeType']=='application/vnd.google-apps.folder':
  #it is a folder
  file_list = mac_lib.search_files_in_drive(drive, mac_folder_id, '.mac')
else:
  #it is a single file: check if it is a mac file
  if mac_file['title'].endswith('.mac'):
    file_list = [mac_file]

print('Ready to process ' + str(len(file_list)) +  ' files')

"""# Core Algorithm and report generation"""

rep_name = 'Iguazu_TEM4'
complete_report = False
prefault_analysis = True
filter_door = True
start_date = None
#start_date = '20201130'     # start date of the acquisition to be processed: string format yyyymmdd
#end_date = '20201206'             # end   date of the acquisition to be processed: string format yyyymmdd
### create the spreadsheet report  ##
from datetime import datetime, timedelta
now = datetime.now()
title = 'report_'+ rep_name +'_'+ str(now)
# create a spreadsheet in a folder (by id)
report = gc.create(title, folder = rep_folder_id)
#rename the first sheet
report.sheet1.title='report'
report_ws = report.sheet1
# create first row (header)
recap_header = ['N', 'Acquisition', 'ACU', 'MCU', 'Setting Part', 'Gese Version','Folder', 'Occurences', 'Mci errors', 'Prefaults', 'MCU resets',  'Details', 'Duration [h]']
row_recap = 0
N= 1
report_ws.insert_rows(row=row_recap, values=recap_header)
row_recap +=1
back_to_first_str = ['=HYPERLINK("#gid=%s","Back to first page")' %(str(report_ws.id),)]
total_duration = 0
for file in file_list:
  file_id   = file['id']
  file_name = file['title']
  
  if (start_date):
    try:
      #check the date
      m = re.findall(r"(?:_\d*)", file_name)
      datetime_str = m[-2][1:]
      acq_dt = datetime.strptime(datetime_str, '%Y%m%d')
      start_dt = datetime.strptime(start_date, '%Y%m%d')
      
      if (acq_dt <= start_dt):  # if the acq is earlier than the start date
        continue                # skip it
      if (end_date):            # if end_date is provided and
        end_dt = datetime.strptime(end_date, '%Y%m%d') 
        if(acq_dt >= end_dt):   # if the acq is later than end date
          continue              # skip it
    except Exception as ex:
      print('error while analysing date format in ' + file_name)
      pass

  try:
    
    # create the mac object
    mac_obj = MacObject((drive,file_id))
    
    ### extra machine info ###
    acq_str = '=HYPERLINK("%s","%s")' %(file['alternateLink'],file['title'])
    folder_id = drive.CreateFile({'id': file['parents'][0]['id']})
    mcu_info = mac_obj.mcu_info['prj_name'] + ' ' + mac_obj.mcu_info['fw_v']
    machine_info = [acq_str, mac_obj.acu_info['fw_v'], mcu_info,mac_obj.acu_info['setting_n'], mac_obj.acu_info['gese_v'], folder_id['title']]

    ### Extract data from acquisition  ###
    acq_data_df = mac_obj.extract_acq()

    ### Extract data from win log ###
    win_log_data_df = mac_obj.extract_win_log()    
    results = mac_lib.process_df(win_log_data_df,'MCI_errors_API220_log')
    results_reset = mac_lib.process_df(win_log_data_df,'MCU_Anomalous_Reset')
    #print(results_reset)
    ### filter out MCI errors when the door is not locked (Windy Strip\Full architecture) ###
    #
    if filter_door == True:
      res_filt = results
      try:
        df_filt = acq_data_df[acq_data_df["Door_Locked"] == 0].groupby((acq_data_df["Door_Locked"] != 0).cumsum())
        for dfs in df_filt:
          tstart = dfs[1].iloc[0]['DateTime']
          tend = dfs[1].iloc[-1]['DateTime']
          res_filt = res_filt[(res_filt["Time"] < tstart) | (res_filt["Time"] > tend)]

        results = res_filt
      except Exception as ex:
        print('error while removing error if door is not locked in ' + file_name)

    # manage date time format
    if '.' in win_log_data_df['Time'].iloc[-1]:
      format_dt = None
    else:
      format_dt = "%m/%d/%Y %H:%M:%S %f"

    duration_dt = pd.to_datetime(win_log_data_df['Time'].iloc[-1], format = format_dt) - pd.to_datetime(win_log_data_df['Time'].iloc[0], format = format_dt)
    if (total_duration == 0):
      total_duration = duration_dt
    else:
      total_duration = total_duration + duration_dt

    #print(str(total_duration))
    #duration = [str(pd.to_datetime(win_log_data_df['Time'].iloc[-1]) - pd.to_datetime(win_log_data_df['Time'].iloc[0]))]
    #duration = [str(duration_dt)]
    duration = ["{:.2f}".format(duration_dt.total_seconds() / 3600.0)]

    ### get recap data from result ###
    recap_data = mac_lib.recap_results(results,'MCI_errors_API220_log','raw')


    if prefault_analysis:
      prefault_results = mac_lib.process_df(acq_data_df,'Prefault')
      ### get recap data from result ###
      prefault_recap_data = mac_lib.recap_results(prefault_results,'Prefault','raw')
    else:
      prefault_recap_data = ['-']


    reset_recap_data = ['-']

    if (complete_report and (not(results.empty) or not(results_reset.empty))):
      if (not(results.empty)):
        ### adding some context to the results
        try:
          #tform = '%m-%d-%Y %H:%M:%S.%f'
          tform = '%m/%d/%Y %H:%M:%S.%f'
          acq_data_df['DateTime'] = pd.to_datetime(acq_data_df['DateTime'], format=tform, errors='coerce')
          dates = pd.to_datetime(results['Time'], format=tform, errors='coerce')
          speed = []
          cycle = []
          phase = []
          step = []
          for dt in dates:
            dt_2 = dt - timedelta(seconds=2)
            speed.append(max(abs(acq_data_df[(acq_data_df['DateTime']>=dt_2) & (acq_data_df['DateTime']<=dt)]['Drum_Velocity'])))
            cycle.append(acq_data_df[(acq_data_df['DateTime']>=dt_2) & (acq_data_df['DateTime']<=dt)]['Cycle'].iloc[0])
            phase.append(acq_data_df[(acq_data_df['DateTime']>=dt_2) & (acq_data_df['DateTime']<=dt)]['Phase'].iloc[0])
            step.append(acq_data_df[(acq_data_df['DateTime']>=dt_2) & (acq_data_df['DateTime']<=dt)]['Step'].iloc[0])
      
          results["Drum_Velocity"] = speed
          results["Cycle"] = cycle
          results["Phase"] = phase
          results["Step"] = step

          if not(results_reset.empty):
            #appending results reset
            results = results.append(results_reset, ignore_index=True, sort=False)
            reset_recap_data = [len(results_reset)]

        except:
          pass

      else:
        results = results_reset



      ### write to spreadsheet - mci errors ###
      wks_new = report.add_worksheet(file_name)
      wks_new.rows = results.shape[0] + 50
      wks_new.insert_rows(row=1, values = back_to_first_str)
      wks_new.set_dataframe(results, (3, 1))

      if prefault_analysis:
        ### write to spreadsheet - prefaults ###
        wks_new.set_dataframe(prefault_results[['DateTime','Prefault']],(len(results)+10,1))


      link_details = ['=HYPERLINK("#gid=%s","%s")' %(str(wks_new.id),file['title'])]
    else:
      link_details = ['-']

    ### update the recap sheet ###
    empty_data = ['']
    # one row for each error - if any error is present
    if ((prefault_recap_data) or (not(isinstance(recap_data, list)))): 
      if not(isinstance(recap_data, list)):
        for key,value in recap_data.items():
          report_ws.insert_rows(row=row_recap, values=[str(N)] + machine_info + [str(value)] + [key] + empty_data + reset_recap_data  + link_details + duration) 
          row_recap +=1

      for key,value in prefault_recap_data.items():
        report_ws.insert_rows(row=row_recap, values=[str(N)] + machine_info + [str(value)] + empty_data + [key] + reset_recap_data + link_details + duration) 
        row_recap +=1
    else:
      report_ws.insert_rows(row=row_recap, values=[str(N)] + machine_info + ['0'] + recap_data + ['-'] + reset_recap_data + link_details + duration)
      row_recap +=1
    
  except Exception as ex:
    report_ws.insert_rows(row =row_recap, values = ['error'] + [file_name] +['id: '] + [file_id])
    row_recap +=1
    template = "An exception of type {0} occurred. Arguments:\n{1!r}"
    message = template.format(type(ex).__name__, ex.args)
    print(message)
    
  N +=1

